### ISSUE TITLE
[QUESTION]: Any way to use this with leiningen?

### ISSUE THREAD

**Issue by jimpil** [seancorfield/build-uber-log4j2-handler#3]
I was recently bitten by the whole log4j2 `plugins-in-uberjar` conundrum, and I can see that this has been an issue for the past 4 years (at least). Your instructions on the README are great, but I'm using leiningen in my project...any way to leverage this? Many thanks in advance...

**Comment by seancorfield** [comment]
Looks like https://github.com/arctype-co/log4j2-plugins-cache will do the same thing but for Leiningen. There may be other Leiningen plugins -- that was just the first I found via Bing.
